// styles.js
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f4f4f4",
  },
  cameraContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  camera: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  scanButton: {
    backgroundColor: "tomato",
    padding: 15,
    borderRadius: 8,
    margin: 20,
    alignItems: "center",
  },
  scanButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  scanResultContainer: {
    padding: 20,
    backgroundColor: "#fff",
    borderRadius: 8,
    margin: 20,
    alignItems: "center",
  },
  scanResultText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  searchBar: {
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    marginBottom: 10,
    paddingLeft: 10,
    borderRadius: 8,
    backgroundColor: "#fff",
    alignSelf: "center",
    width: "80%",
  },
  listItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    width: "100%",
    justifyContent: "flex-start",
  },
  logo: {
    width: "20%",
    height: 100,
    marginTop: 20,
    marginBottom: 10,
    alignSelf: "center",
    resizeMode: "contain",
    alignItems: "center",
  },
  itemImage: {
    flex: 1,
    resizeMode: "contain",
    justifyContent: "center",
    alignItems: "center",
    height: 200,
    width: 100,
  },
  headerText: {
    alignSelf: "center",
    marginBottom: 10,
    marginLeft: 20,
    fontWeight: "900",
  },
  itemCountText: {
    marginLeft: 10,
    marginTop: 10,
    marginBottom: 10,
    fontWeight: "900",
  },
  sectionHeader: {
    backgroundColor: "#f4f4f4",
    padding: 10,
    marginLeft: 10,
    fontSize: 30,
    fontWeight: "bold",
  },
  detailImage: {
    width: "100%",
    height: 200,
    resizeMode: "cover",
  },
  urlContainer: {
    backgroundColor: "#e0e0e0",
    padding: 5,
    marginTop: 5,
    borderRadius: 5,
  },

  urlText: {
    color: "#333",
  },
  headerText: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
  },
  detailImage: {
    width: "100%",
    height: 200,
    resizeMode: "cover",
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 10,
  },
  newsArticleContainer: {
    marginBottom: 20,
  },
  newsArticleImage: {
    width: "100%",
    height: 200,
    resizeMode: "cover",
    borderRadius: 10,
    marginBottom: 10,
  },
  newsArticleTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  newsArticleDescription: {
    fontSize: 16,
    color: "#555",
  },
  urlText: {
    fontSize: 16,
    color: "#0066cc",
    textDecorationLine: "underline",
    marginBottom: 10,
  },
  source: {
    fontSize: 16,
    color: "#0066cc",
    textDecorationLine: "underline",
    marginTop: 5,
  },
  descriptionText: {
    fontWeight: "900",
    color: "white",
    backgroundColor: "teal",
    padding: 5,
  },
  urlContainer: {
    marginBottom: 20,
  },
  urlText: {
    fontSize: 22,
    color: "#111",
    fontWeight: "900",
    marginBottom: 5,
  },
  urlImage: {
    width: "100%",
    height: 150,
    resizeMode: "cover",
    borderRadius: 10,
    marginBottom: 10,
  },
  linkDateText: {
    fontSize: 14,
    color: "#888",
  },
  listItem: {
    margin: 10,
    padding: 10,
    backgroundColor: "#FFF",
    borderRadius: 8,
    elevation: 4,
  },
  itemImage: {
    width: "100%",
    height: 200,
    overflow: "hidden",
    position: "relative",
  },
  joinBoycottButton: {
    position: "absolute",
    top: 0,
    right: 0,
    alignSelf: "center",
    backgroundColor: "#000",
    padding: 10,
  },
  joinBoycottButtonText: {
    fontWeight: "bold",
    color: "white",
  },
  imageBackground: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
    alignItems: "center",
    height:200,
    width: "100%",
  },
  peopleJoined: {
    backgroundColor: "#00cbaf",
    width: 70,
    padding: 5,
    marginTop: 0,
    borderRadius: 0,
  },
  joinCountText: {
    fontWeight: "bold",
    position: "absolute",
    top: 10,
    left: 10,
    marginLeft: 5,
    color: "white",
    zIndex: 100,
  },
  dynamicHeaderContainer: {
    backgroundColor: "#fff",
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  dynamicHeaderText: {
    fontWeight: "bold",
    fontSize: 16,
  },
  fixedDynamicHeaderContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: "#ccc",
    alignItems: "center",
    justifyContent: "center",
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
  },
  logoContainer: {
    marginRight: 16,
  },
  logo: {
    width: 40,
    height: 40,
  },
  searchBarContainer: {
    flex: 1,
  },
  searchBar: {
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 8,
    paddingLeft: 12,
  },
});

export default styles;